### ISSUE TITLE
ar-playground/events.js is not available

### ISSUE THREAD

**Issue by shubhamraghav1** [nicolocarpignoli/nicolocarpignoli.github.io#1]
What happened to the link "https://rawgit.com/nicolocarpignoli/nicolocarpignoli.github.io/master/ar-playground/events.js"
its not working now. the file event.js is missing in ar playground

**Comment by nicolocarpignoli** [comment]
Hi, it was removed because ar-playground is not using it anymore. All events and scripts are used on the other folders like ar-click-events, for example.

**Comment by nicolocarpignoli** [comment]
@shubhamraghav1 where do you still see that file URL? maybe in some Medium article?
